window.presentDayArticles = [
    // Crude
    { id: "present_1", category: 'Crude Oil', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/oil-hits-five-month-high-after-us-hits-key-iranian-nuclear-sites-2025-06-23/', premium: false },
    { id: "present_2", category: 'Crude Oil', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/goldman-sachs-warns-rising-risks-energy-supply-sees-potential-surge-oil-prices-2025-06-23/', premium: false },
    { id: "present_3", category: 'Crude Oil', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/world/asia-pacific/south-koreas-lee-says-middle-east-situation-is-very-urgent-2025-06-23/', premium: false },
    { id: "present_4", category: 'Crude Oil', title: '', date: 'June 23, 2025', source: 'IndiaTimes', link: 'https://indiatimes.com/trending/us-warns-iran-against-closing-strait-of-hormuz-calling-it-economic-suicide-urges-china-to-intervene-amid-rising-tensions-661753.html', premium: false },
    { id: "present_5", category: 'Crude Oil', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/world/india/rupee-under-fire-after-us-strikes-iran-jolt-oil-stoke-risk-aversion-2025-06-23/', premium: false },
    // Natural Gas
    { id: "present_6", category: 'Natural Gas', title: '', date: 'June 23, 2025', source: 'OGCI', link: 'https://www.ogci.com/news/ogci-expands-methane-library-with-new-features-and-content-to-accelerate-emissions-reductions/', premium: false },
    { id: "present_7", category: 'Natural Gas', title: '', date: 'June 23, 2025', source: 'FX Empire', link: 'https://www.fxempire.com/forecasts/article/natural-gas-and-oil-forecast-rising-geopolitical-risk-fuels-energy-market-volatility-1527884?utm_source=chatgpt.com', premium: false },
    { id: "present_8", category: 'Natural Gas', title: '', date: 'June 23, 2025', source: 'Economies', link: 'https://www.economies.com/commodities/natural-gas-analysis/natural-gas-price-gathers-some-gains%E2%80%93-forecast-today-%E2%80%93-23-6-2025-118967?utm_source=chatgpt.com', premium: false },
    { id: "present_9", category: 'Natural Gas', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/lng-canada-produces-first-liquefied-natural-gas-export-sources-say-2025-06-22/?utm_source=chatgpt.com', premium: false },
    { id: "present_10", category: 'Natural Gas', title: '', date: 'June 23, 2025', source: 'TradingView', link: 'https://www.tradingview.com/news/te_news%3A464708%3A0-uk-natural-gas-futures-rise-to-near-3-month-high/?utm_source=chatgpt.com', premium: false },
    { id: "present_11", category: 'Natural Gas', title: '', date: 'June 23, 2025', source: 'DailyForex', link: 'https://www.dailyforex.com/forex-technical-analysis/2025/06/natural-gas-forecast-23-june-2025/230059?utm_source=chatgpt.com', premium: false },
    { id: "present_12", category: 'Natural Gas', title: '', date: 'June 23, 2025', source: 'gCaptain', link: 'https://gcaptain.com/lng-canada-produces-first-liquefied-natural-gas-for-export/', premium: false },
    // Petrochemicals
    { id: "present_13", category: 'Petrochemicals', title: '', date: 'June 23, 2025', source: 'MK', link: 'https://www.mk.co.kr/en/business/11350265', premium: false },
    { id: "present_14", category: 'Petrochemicals', title: '', date: 'June 23, 2025', source: 'ICIS', link: 'https://www.icis.com/explore/resources/news/2025/06/23/11112954/asia-petrochemical-shares-fall-oil-rises-as-us-enters-israel-iran-war/?utm_source=chatgpt.com', premium: false },
    { id: "present_15", category: 'Petrochemicals', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/goldman-sachs-warns-rising-risks-energy-supply-sees-potential-surge-oil-prices-2025-06-23/?utm_source=chatgpt.com', premium: false },
    { id: "present_16", category: 'Petrochemicals', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/world/china/tankers-u-turn-zig-zag-pause-around-strait-hormuz-2025-06-23/?utm_source=chatgpt.com', premium: false },
    { id: "present_17", category: 'Petrochemicals', title: '', date: 'June 23, 2025', source: 'Argus Media', link: 'https://www.argusmedia.com/en/news-and-insights/latest-market-news/2701947-indian-quality-controls-for-pvc-set-for-december-2025?utm_source=chatgpt.com', premium: false },
    // Power
    { id: "present_18", category: 'Power', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/forget-ai-keeping-cool-is-bigger-power-sector-problem-2025-06-23/?utm_source=chatgpt.com', premium: false },
    { id: "present_19", category: 'Power', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/spanish-utilities-lobby-says-power-plants-complied-with-grid-operator-during-2025-06-23/?utm_source=chatgpt.com', premium: false },
    { id: "present_20", category: 'Power', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/wall-street-futures-edge-higher-investors-await-irans-retaliatory-move-2025-06-23/?utm_source=chatgpt.com', premium: false },
    { id: "present_21", category: 'Power', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/world/middle-east/us-attack-iran-adds-economic-uncertainty-2025-06-23/?utm_source=chatgpt.com', premium: false },
    { id: "present_22", category: 'Power', title: '', date: 'June 23, 2025', source: 'Organiser', link: 'https://organiser.org/2025/06/23/298603/bharat/lights-on-shortages-gone-india-cuts-power-shortages-from-4-2-to-0-1-in-a-decade-with-100-village-electrification/?utm_source=chatgpt.com', premium: false },
    { id: "present_23", category: 'Power', title: '', date: 'June 23, 2025', source: 'The National', link: 'https://www.thenational.com.pg/transformers-can-cut-down-outages-in-city/?utm_source=chatgpt.com', premium: false },
    { id: "present_24", category: 'Power', title: '', date: 'June 23, 2025', source: 'Arab Times', link: 'https://www.arabtimesonline.com/news/kuwait-calls-on-public-to-help-avoid-power-cuts-with-simple-energy-saving-steps/?utm_source=chatgpt.com', premium: false },
    // Renewables
    { id: "present_25", category: 'Renewables', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/sustainability/climate-energy/italys-eni-sells-20-plenitude-unit-ares-2-billion-euros-2025-06-23/?utm_source=chatgpt.com', premium: false },
    { id: "present_26", category: 'Renewables', title: '', date: 'June 23, 2025', source: 'Economic Times', link: 'https://economictimes.indiatimes.com/industry/renewables/adani-commissions-indias-first-off-grid-5-mw-green-hydrogen-plant-in-gujarat/articleshow/122019721.cms?utm_source=chatgpt.com', premium: false },
    { id: "present_27", category: 'Renewables', title: '', date: 'June 23, 2025', source: 'Reuters', link: 'https://www.reuters.com/sustainability/climate-energy/octopus-energy-dtek-raise-115-million-ukraine-solar-battery-projects-2025-06-23/?utm_source=chatgpt.com', premium: false },
    { id: "present_28", category: 'Renewables', title: '', date: 'June 23, 2025', source: 'RWE', link: 'https://www.rwe.com/en/press/rwe-renewables-europe-australia/2025-06-23-rwes-theodore-wind-farm-project-receives-development-approval/?utm_source=chatgpt.com', premium: false },
    { id: "present_29", category: 'Renewables', title: '', date: 'June 23, 2025', source: 'Energy Global', link: 'https://www.energyglobal.com/solar/23062025/europes-largest-floating-solar-power-plant-now-operational-in-france/?utm_source=chatgpt.com', premium: false },
    { id: "present_30", category: 'Renewables', title: '', date: 'June 23, 2025', source: 'BW Group', link: 'https://bw-group.com/newsroom/articles/2025/06/bw-ess-and-ibersun-sign-joint-venture-to-develop-2-2gw-bess-in-spain/?utm_source=chatgpt.com', premium: false },
    // Company News
    { id: "present_31", category: 'Company News', title: '', date: 'June 23, 2025', source: 'SolarQuarter', link: 'https://solarquarter.com/2025/06/23/masdar-ceo-leads-delegation-to-terra-gen-renewable-project-sites-in-california/?utm_source=chatgpt.com', premium: false },
    { id: "present_32", category: 'Company News', title: '', date: 'June 23, 2025', source: 'The Week', link: 'https://www.theweek.in/wire-updates/business/2025/06/23/dcm15-biz-blupine-debt.html?utm_source=chatgpt.com', premium: false },
    { id: "present_33", category: 'Company News', title: '', date: 'June 23, 2025', source: 'Moneycontrol', link: 'https://www.moneycontrol.com/news/business/stocks/waaree-renewables-inks-mou-for-100-mwp-international-solar-project-alpha-article-13162686.html?utm_source=chatgpt.com', premium: false },
    { id: "present_34", category: 'Company News', title: '', date: 'June 23, 2025', source: 'Angel One', link: 'https://www.angelone.in/news/ntpc-achieves-full-commercial-operation-of-nokh-solar-project-s-plot-3?utm_source=chatgpt.com', premium: false },
    { id: "present_35", category: 'Company News', title: '', date: 'June 23, 2025', source: 'Energy Magazine', link: 'https://www.energymagazine.com.au/partnership-announced-for-nsw-pumped-hydro-project/?utm_source=chatgpt.com', premium: false },
    { id: "present_36", category: 'Company News', title: '', date: 'June 23, 2025', source: 'PV Magazine', link: 'https://www.pv-magazine.com/press-releases/envision-energy-enters-french-energy-storage-market-as-it-is-contracted-to-provide-120-mw-240-mwh-turnkey-project-for-kallista-energy/?utm_source=chatgpt.com', premium: false },
    { id: "present_37", category: 'Company News', title: '', date: 'June 23, 2025', source: 'TradingView', link: 'https://www.tradingview.com/news/moneycontrol%3A0c5becfe8094b%3A0-adani-enterprises-unit-commissions-india-s-first-off-grid-green-hydrogen-pilot-plant-shares-rise-1-5/?utm_source=chatgpt.com', premium: false }
];
