// /js/articles_present.js
// Data is assigned to the global 'window' object to be accessible by other scripts.
window.presentDayArticles = [
    // Crude
    { id: "present_1", category: 'Crude Oil', title: 'Global Stocks Fall, Oil Futures Rise on a Report U.S. May Soon Strike Iran', date: 'June 19, 2025', source: 'MarketWatch', link: 'https://www.marketwatch.com/story/global-stocks-fall-oil-futures-rise-on-a-report-u-s-may-soon-strike-iran-234f474e?utm_source=chatgpt.com', premium: false },
    { id: "present_2", category: 'Crude Oil', title: 'Russia, US, Saudi Arabia Could Act Jointly to Stabilise Oil', date: 'June 19, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/russias-dmitriev-says-russia-us-saudi-arabia-could-act-jointly-stabilise-oil-2025-06-19/?utm_source=chatgpt.com', premium: false },
    { id: "present_3", category: 'Crude Oil', title: 'Saudi Energy Minister: Potential Loss of Iranian Oil, We Only React to Realities', date: 'June 19, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/saudi-energy-minister-potential-loss-iranian-oil-we-only-react-realities-2025-06-19/?utm_source=chatgpt.com', premium: false },
    // Natural Gas
    { id: "present_4", category: 'Natural Gas', title: "Asia's Only LNG Bright Spot May Be About to Get Red Hot", date: 'June 19, 2025', source: 'Reuters', link: 'https://www.reuters.com/markets/commodities/asias-only-lng-bright-spot-may-be-about-get-red-hot-2025-06-19/?utm_source=chatgpt.com', premium: false },
    { id: "present_5", category: 'Natural Gas', title: 'Canada Could Begin First Pacific LNG Production This Weekend', date: 'June 19, 2025', source: 'TankTerminals', link: 'https://tankterminals.com/news/canada-could-begin-first-pacific-lng-production-this-weekend/?utm_source=chatgpt.com', premium: false },
    { id: "present_6", category: 'Natural Gas', title: 'FERC Takes Action to Remove Barriers to Building Natural Gas Facilities', date: 'June 19, 2025', source: 'FERC', link: 'https://www.ferc.gov/news-events/news/ferc-takes-action-remove-barriers-building-natural-gas-facilities?utm_source=chatgpt.com', premium: false },
    { id: "present_7", category: 'Natural Gas', title: 'Natural Gas Projects Reboot After Officials Wake Up to Stark Realities', date: 'June 19, 2025', source: 'RealClearEnergy', link: 'https://www.realclearenergy.org/articles/2025/06/19/natural_gas_projects_reboot_after_officials_wake_up_to_stark_realities_1117107.html?utm_source=chatgpt.com', premium: false },
    { id: "present_8", category: 'Natural Gas', title: 'How EU Plans to Ban Russian Gas', date: 'June 19, 2025', source: 'Reuters', link: 'https://www.reuters.com/sustainability/boards-policy-regulation/how-eu-plans-ban-russian-gas-2025-06-17/?utm_source=chatgpt.com', premium: false },
    // Petrochemicals
    { id: "present_9", category: 'Petrochemicals', title: "New Administration Hits the Gas on Revival of Korea's Struggling Petrochemical Industry", date: 'June 19, 2025', source: 'Korea JoongAng Daily', link: 'https://koreajoongangdaily.joins.com/news/2025-06-19/business/economy/New-administration-hits-the-gas-on-revival-of-Koreas-struggling-petrochemical-industry/2334267', premium: false },
    { id: "present_10", category: 'Petrochemicals', title: 'Shawkwei & Partners Completes Acquisition and Delisting of PEC Ltd', date: 'June 19, 2025', source: 'PR Newswire', link: 'https://www.prnewswire.co.uk/news-releases/shawkwei--partners-completes-acquisition-and-delisting-of-pec-ltd-302485353.html', premium: false },
    { id: "present_11", category: 'Petrochemicals', title: 'SP Global Commodity Insights', date: 'June 19, 2025', source: 'S&P Global', link: 'https://www.spglobal.com/commodity-insights/es', premium: false },
    { id: "present_12", category: 'Petrochemicals', title: 'Energy Equation: Shawkwei PEC Acquisition Reinvents Playbook for Energy Transition Leaders', date: 'June 19, 2025', source: 'AInvest', link: 'https://www.ainvest.com/news/energy-equation-shawkwei-pec-acquisition-reinvents-playbook-energy-transition-leaders-2506/', premium: false },
    { id: "present_13", category: 'Petrochemicals', title: 'Chemical Industry Outlook', date: 'June 19, 2025', source: 'Deloitte', link: 'https://www.deloitte.com/us/en/insights/industry/chemicals-and-specialty-materials/chemical-industry-outlook.html', premium: false },
    { id: "present_14", category: 'Petrochemicals', title: 'Chemical Trends H1 2025', date: 'June 19, 2025', source: 'S&P Global', link: 'https://www.spglobal.com/content/dam/spglobal/ci/en/documents/news-research/special-reports/Chemical%20Trends%20H1%202025.pdf', premium: false },
    // Power
    { id: "present_15", category: 'Power', title: 'South Carolina Energy Power Plants Bill Signing', date: 'June 19, 2025', source: 'AP News', link: 'https://apnews.com/article/south-carolina-energy-power-plants-bill-signing-74542913fb3527389ab6de436aeeac11', premium: false },
    { id: "present_16", category: 'Power', title: 'CERC Suggests Wider Over-the-Counter Power Market Scope', date: 'June 19, 2025', source: 'Mercom India', link: 'https://www.mercomindia.com/daily-news-wrap-up-cerc-suggests-wider-over-the-counter-power-market-scope', premium: false },
    { id: "present_17", category: 'Power', title: 'New Marine Energy Taskforce Sets Sights on £50bn Tidal Power Potential', date: 'June 19, 2025', source: 'Energy Live News', link: 'https://www.energylivenews.com/2025/06/19/new-marine-energy-taskforce-sets-sights-on-50bn-tidal-power-potential/', premium: false },
    { id: "present_18", category: 'Power', title: 'North Sea Renewable Energy Wind, Wave and Tidal Projects Map 2025', date: 'June 19, 2025', source: 'Globe Newswire', link: 'https://www.globenewswire.com/news-release/2025/06/19/3102062/28124/en/North-Sea-Renewable-Energy-Wind-Wave-and-Tidal-Projects-Map-2025.html', premium: false },
    { id: "present_19", category: 'Power', title: 'North America Offshore Wind Projects Map 2025', date: 'June 19, 2025', source: 'Globe Newswire', link: 'https://www.globenewswire.com/news-release/2025/06/19/3102063/0/en/North-America-Offshore-Wind-Projects-Map-2025-Great-Lakes-East-Coast-California-and-Hawaii.html', premium: false },
    // Renewables
    { id: "present_20", category: 'Renewables', title: "Realizing Indonesia's Ambitious Renewable Energy Goals Calls New Approach", date: 'June 19, 2025', source: 'IEEFA', link: 'https://ieefa.org/resources/realizing-indonesias-ambitious-renewable-energy-goals-calls-new-approach', premium: false },
    { id: "present_21", category: 'Renewables', title: 'North Sea Renewable Energy Wind, Wave and Tidal Projects Map 2025', date: 'June 19, 2025', source: 'Globe Newswire', link: 'https://www.globenewswire.com/news-release/2025/06/19/3102062/0/en/North-Sea-Renewable-Energy-Wind-Wave-and-Tidal-Projects-Map-2025.html', premium: false },
    { id: "present_22", category: 'Renewables', title: 'EU Greenlights €142.77M in Potential Funding for H2Silesia Hydrogen Project by Polenergia', date: 'June 19, 2025', source: 'FuelCellsWorks', link: 'https://fuelcellsworks.com/2025/06/19/electrolyzer/eu-greenlights-142-77m-in-potential-funding-for-h2silesia-hydrogen-project-by-polenergia', premium: false },
    { id: "present_23", category: 'Renewables', title: 'WEF: Global Energy Transition Picks Up Pace', date: 'June 19, 2025', source: 'Balkan Green Energy News', link: 'https://balkangreenenergynews.com/wef-global-energy-transition-picks-up-pace/', premium: false },
    { id: "present_24", category: 'Renewables', title: "Renewable Energy Firm Citicore Inks $120M Deal with Indonesia's Pertamina NRE", date: 'June 19, 2025', source: 'GMA News', link: 'https://www.gmanetwork.com/news/money/companies/949933/renewable-energy-firm-citicore-inks-120-m-deal-with-indonesia-s-pertamina-nre/story/', premium: false },
    { id: "present_25", category: 'Renewables', title: 'Germany Invests $50 Million in Renewable Energy Workforce Training in Vietnam', date: 'June 19, 2025', source: 'VIR', link: 'https://vir.com.vn/germany-invests-50-million-usd-in-renewable-energy-workforce-training-in-vietnam-130871.html', premium: false },
    // Company News
    { id: "present_26", category: 'Company News', title: 'Willow Biosciences Inc. Announces Completion of Transformative Recapitalization Transactions to Form Atlas Energy Corp.', date: 'June 19, 2025', source: 'Newswire', link: 'https://www.newswire.ca/news-releases/willow-biosciences-inc-announces-completion-of-transformative-recapitalization-transactions-to-form-atlas-energy-corp--854265175.html', premium: false },
    { id: "present_27", category: 'Company News', title: 'Alain Rhéume Announces His Retirement as Chair of the Board of Directors of Boralex', date: 'June 19, 2025', source: 'Globe Newswire', link: 'https://www.globenewswire.com/news-release/2025/06/19/3102197/0/en/Alain-Rh%C3%A9ume-Announces-His-Retirement-as-Chair-of-the-Board-of-Directors-of-Boralex.html', premium: false },
    { id: "present_28", category: 'Company News', title: 'Electra Commences Early Works to Support Restart of North America\'s Only Cobalt Refinery', date: 'June 19, 2025', source: 'Globe Newswire', link: 'https://www.globenewswire.com/news-release/2025/06/19/3102139/0/en/Electra-Commences-Early-Works-to-Support-Restart-of-North-America-s-Only-Cobalt-Refinery.html', premium: false },
    { id: "present_29", category: 'Company News', title: 'Nvidia Backs $650M Funding Round for Bill Gates Nuclear Firm TerraPower', date: 'June 19, 2025', source: 'Tribune', link: 'https://tribune.com.pk/story/2551648/nvidia-backs-650m-funding-round-for-bill-gates-nuclear-firm-terrapower', premium: false }
];
