window.presentDayArticles = [
    // Crude
    { id: "present_1", category: 'Crude Oil', title: 'Oil Set to Rise for Third Week on Escalating Israel-Iran Conflict', date: 'June 20, 2025', source: 'Reuters', link: 'https://www.reuters.com/world/middle-east/oil-set-rise-third-week-escalating-israel-iran-conflict-2025-06-20/?utm_source=chatgpt.com', premium: false },
    { id: "present_10", category: 'Petrochemicals', title: 'China, SE Asia Olefins Outlook for 2025: Poor Profitability to Dominate', date: 'June 20, 2025', source: 'ChemOrbis', link: 'https://www.chemorbis.com/en/plastics-news/China-SE-Asia-Olefins-outlook-for-2025-Poor-profitability-to-dominate-ethylene-propylene-value-ch/2024/12/27/921292%26isflashhaber%3Dtrue?utm_source=chatgpt.com#reportH', premium: false },
    { id: "present_14", category: 'Power', title: 'Floating Offshore Wind Power Industry', date: 'June 20, 2025', source: 'Yahoo Finance', link: 'https://finance.yahoo.com/news/floating-offshore-wind-power-industry-093400225.html?utm_source=chatgpt.com', premium: false },
    { id: "present_16", category: 'Power', title: 'EIA Short-Term Energy Outlook', date: 'June 20, 2025', source: 'EIA', link: 'https://www.eia.gov/outlooks/steo/?utm_source=chatgpt.com', premium: false },
    { id: "present_22", category: 'Renewables', title: 'Envision Energy Enters French Energy Storage Market', date: 'June 20, 2025', source: 'StreetInsider', link: 'https://www.streetinsider.com/PRNewswire/Envision+Energy+enters+French+energy+storage+market+as+it+is+contracted+to+provide+120+MW+240+MWh+turnkey+project+for+Kallista+Energy/24956958.html', premium: false },
    { id: "present_2", category: 'Crude Oil', title: 'Global Markets Oil Graphic', date: 'June 20, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/global-markets-oil-graphic-2025-06-20/?utm_source=chatgpt.com', premium: false },
    { id: "present_3", category: 'Crude Oil', title: 'US, Chinese Strategic Reserve Buys May Offset Oil Surplus: Russia\'s Gazprom Neft', date: 'June 20, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/us-chinese-strategic-reserve-buys-may-offset-oil-surplus-russias-gazprom-neft-2025-06-20/?utm_source=chatgpt.com', premium: false },
    { id: "present_4", category: 'Crude Oil', title: 'Global Markets Wrapup', date: 'June 20, 2025', source: 'Reuters', link: 'https://www.reuters.com/world/china/global-markets-wrapup-1-2025-06-20/?utm_source=chatgpt.com', premium: false },
    { id: "present_5", category: 'Crude Oil', title: 'Oil Prices Fall as Trump Leaves Room for Diplomacy in Israel-Iran Conflict', date: 'June 20, 2025', source: 'Türkiye Today', link: 'https://www.turkiyetoday.com/business/oil-prices-fall-as-trump-leaves-room-for-diplomacy-in-israel-iran-conflict-3203142?utm_source=chatgpt.com', premium: false },
    // Natural Gas
    { id: "present_6", category: 'Natural Gas', title: 'Mozambique Energy Minister Optimistic on TotalEnergies Plan to Resume LNG Project', date: 'June 20, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/mozambique-energy-minister-optimistic-totalenergies-plan-resume-lng-project-2025-06-20/?utm_source=chatgpt.com', premium: false },
    { id: "present_7", category: 'Natural Gas', title: 'JERA, Woodside Energy Agree Supply Deal During Winter Months', date: 'June 20, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/jera-woodside-energy-agree-supply-deal-during-winter-months-2025-06-20/?utm_source=chatgpt.com', premium: false },
    { id: "present_8", category: 'Natural Gas', title: 'Natural Gas Price & Chart', date: 'June 20, 2025', source: 'Trading Economics', link: 'https://tradingeconomics.com/commodity/natural-gas', premium: false },
    { id: "present_9", category: 'Natural Gas', title: 'Natural Gas Price Keeps Rising – Forecast Today', date: 'June 20, 2025', source: 'Economies', link: 'https://www.economies.com/commodities/natural-gas-analysis/natural-gas-price-keeps-rising%E2%80%93-forecast-today-%E2%80%93-20-6-2025-118937?utm_source=chatgpt.com', premium: false },
    // Petrochemicals
    { id: "present_11", category: 'Petrochemicals', title: 'China\'s PE Market Update', date: 'June 20, 2025', source: 'Sunsirs', link: 'https://www.sunsirs.com/uk/detail_news-24831.html?utm_source=chatgpt.com', premium: false },
    { id: "present_12", category: 'Petrochemicals', title: 'Eni Unveils Plant for Chemical Recycling of Plastic Waste', date: 'June 20, 2025', source: 'Reuters', link: 'https://www.reuters.com/sustainability/land-use-biodiversity/eni-unveils-plant-chemical-recycling-plastic-waste-2025-06-19/?utm_source=chatgpt.com', premium: false },
    { id: "present_13", category: 'Petrochemicals', title: 'Polymer Market News', date: 'June 20, 2025', source: 'PolymerUpdate', link: 'https://www.polymerupdate.com/News/Details/1379453?utm_source=chatgpt.com', premium: false },
    // Power
    { id: "present_15", category: 'Power', title: 'Nessel Challenges Order to Keep J.H. Campbell Plant Open as Energy Experts Predict Price Hikes', date: 'June 20, 2025', source: 'Michigan Advance', link: 'https://michiganadvance.com/2025/06/20/nessel-challenges-order-to-keep-j-h-campbell-plant-open-as-energy-experts-predict-price-hikes/?utm_source=chatgpt.com', premium: false },
    { id: "present_17", category: 'Power', title: 'High French River Temperatures Hit Nuclear Production Next Week', date: 'June 20, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/high-french-river-temperatures-hit-nuclear-production-next-week-2025-06-20/?utm_source=chatgpt.com', premium: false },
    { id: "present_18", category: 'Power', title: 'IEA Electricity 2025 Executive Summary', date: 'June 20, 2025', source: 'IEA', link: 'https://www.iea.org/reports/electricity-2025/executive-summary?utm_source=chatgpt.com', premium: false },
    { id: "present_19", category: 'Power', title: 'Duke Energy Offers Tips to Save Energy and Money as Temperatures Rise in the Carolinas', date: 'June 20, 2025', source: 'PR Newswire', link: 'https://www.prnewswire.com/news-releases/duke-energy-offers-tips-to-save-energy-and-money-as-temperatures-rise-in-the-carolinas-302486614.html?utm_source=chatgpt.com', premium: false },
    { id: "present_20", category: 'Power', title: 'Georgia Power\'s Tips & Resources for Summer Energy Bills', date: 'June 20, 2025', source: '11Alive', link: 'https://www.11alive.com/article/money/consumer/georgia-powers-tips-resources-summer-energy-bills/85-a365edc4-3d93-42f6-aa28-6e7b6db367f5?utm_source=chatgpt.com', premium: false },
    // Renewables
    { id: "present_21", category: 'Renewables', title: 'Poland Allocates EUR 633 Million for Six Green Hydrogen Production Projects', date: 'June 20, 2025', source: 'Renewable Watch', link: 'https://renewablewatch.in/2025/06/20/poland-allocates-eur-633-million-for-six-green-hydrogen-production-projects/?utm_source=chatgpt.com', premium: false },
    { id: "present_23", category: 'Renewables', title: 'MET Group Inaugurates Hungary\'s Largest Battery', date: 'June 20, 2025', source: 'Renewable Energy Magazine', link: 'https://www.renewableenergymagazine.com/storage/met-group-inaugurates-hungarya-s-largest-battery-20250620?utm_source=chatgpt.com', premium: false },
    { id: "present_24", category: 'Renewables', title: 'Mobility Plaza News', date: 'June 20, 2025', source: 'Mobility Plaza', link: 'https://www.mobilityplaza.org/news/41722?utm_source=chatgpt.com', premium: false },
    { id: "present_25", category: 'Renewables', title: 'Metacon Wins Green Hydrogen Project in Morocco', date: 'June 20, 2025', source: 'MEED', link: 'https://www.meed.com/metacon-wins-green-hydrogen-project-in-morocco?utm_source=chatgpt.com', premium: false },
    // Company News
    { id: "present_26", category: 'Company News', title: 'Italy\'s ENI Eyes New Unit to Manage Oil Refineries, Unions Say', date: 'June 20, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/italys-eni-eyes-new-unit-manage-oil-refineries-unions-say-2025-06-20/?utm_source=chatgpt.com', premium: false },
    { id: "present_27", category: 'Company News', title: 'Texas Creating Task Forces to Target Permian Basin Oil Field Thefts', date: 'June 20, 2025', source: 'KSAT', link: 'https://www.ksat.com/news/texas/2025/06/20/texas-creating-task-forces-to-target-permian-basin-oil-field-thefts/?utm_source=chatgpt.com', premium: false },
    { id: "present_28", category: 'Company News', title: 'Eon Resources Inc. Announces Eon Energy LLC Has Agreed to Acquire South Justis Field in the Permian Basin', date: 'June 20, 2025', source: 'WebDisclosure', link: 'https://www.webdisclosure.com/press-release/eon-resources-inc-announces-eon-energy-llc-has-agreed-to-acquire-south-justis-field-in-the-permian-basin-in-lea-county-new-mexico-with-207-million-barrels-of-original-oil-in-place-on-5360-acres-FTHbrQAyVGO?utm_source=chatgpt.com', premium: false }
];
