// /js/articles_premium.js
// Data is assigned to the global 'window' object to be accessible by other scripts.
window.premiumArticles = [
    // Crude
    { id: "prem_1", category: 'Crude Oil', title: 'Mideast Conflict Turbocharges Diesel Prices, Squeezing Europe', date: 'June 19, 2025', source: 'Reuters', link: 'https://www.reuters.com/markets/commodities/mideast-conflict-turbocharges-diesel-prices-squeezing-europe-2025-06-19/?utm_source=chatgpt.com', premium: true },
    { id: "prem_2", category: 'Crude Oil', title: 'Crude Oil Prices Swing Amid War Escalation Risk', date: 'June 19, 2025', source: 'Times of India', link: 'https://timesofindia.indiatimes.com/business/international-business/crude-oil-prices-swing-amid-war-escalation-risk/articleshow/121943087.cms?utm_source=chatgpt.com', premium: true },
    { id: "prem_3", category: 'Crude Oil', title: 'Brent Crude Prices Expected to Average $70 in FY26 Despite Israel-Iran Conflict', date: 'June 19, 2025', source: 'Times of India', link: 'https://timesofindia.indiatimes.com/business/international-business/fundamentally-well-supplied-brent-crude-prices-expected-to-average-70-in-fy26-despite-israel-iran-conflict-says-report/articleshow/121949211.cms?utm_source=chatgpt.com', premium: true },
    // Nat Gas
    { id: "prem_4", category: 'Natural Gas', title: 'Rapid Read: Geopolitical Must-Knows for Today', date: 'June 19, 2025', source: 'GeopoliticsUnplugged', link: 'https://geopoliticsunplugged.substack.com/p/rapid-read-geopolitical-must-knows-914?utm_source=chatgpt.com', premium: true },
    { id: "prem_5", category: 'Natural Gas', title: 'Russia to Keep Shipping Gas, Oil to Hungary, Hungarian Foreign Minister Says', date: 'June 19, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/russia-keep-shipping-gas-oil-hungary-hungarian-foreign-minister-says-2025-06-19/?utm_source=chatgpt.com', premium: true },
    { id: "prem_6", category: 'Natural Gas', title: 'Best in Energy: 19 June 2025', date: 'June 19, 2025', source: 'JKemp Energy', link: 'https://jkempenergy.com/2025/06/19/best-in-energy-19-june-2025/?utm_source=chatgpt.com', premium: true },
    { id: "prem_7", category: 'Natural Gas', title: 'Canada Could Produce First LNG by This Weekend, Sources Say', date: 'June 19, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/canada-could-produce-first-lng-by-this-weekend-sources-say-2025-06-18/?utm_source=chatgpt.com', premium: true },
    // Petrochemicals
    { id: "prem_8", category: 'Petrochemicals', title: '40th World Petrochemical Conference to Discuss Outlook, Recovery', date: 'June 19, 2025', source: 'Stock Titan', link: 'https://www.stocktitan.net/news/SPGI/40th-world-petrochemical-conference-to-discuss-outlook-recovery-for-a8u6v59i0zt0.html', premium: true },
    { id: "prem_9", category: 'Petrochemicals', title: 'Geopolitical Crossroads: Navigating Oil Markets, Energy Equities, Middle East Tensions', date: 'June 19, 2025', source: 'AInvest', link: 'https://www.ainvest.com/news/geopolitical-crossroads-navigating-oil-markets-energy-equities-middle-east-tensions-2506/?utm_source=chatgpt.com', premium: true },
    { id: "prem_10", category: 'Petrochemicals', title: 'NextGen 2025 Session on Petrochemicals: A Mega Opportunity for India', date: 'June 19, 2025', source: 'Indian Chemical News', link: 'https://www.indianchemicalnews.com/petro-chemical/nextgen-2025-session-on-petrochemicals-a-mega-opportunity-for-india-to-discuss-future-roadmap-of-petrochemicals-26485?utm_source=chatgpt.com', premium: true },
    { id: "prem_11", category: 'Petrochemicals', title: 'Korea Designates Yeosu as Industrial Crisis Response Area to Support Petrochemical Firms', date: 'June 19, 2025', source: 'Korea JoongAng Daily', link: 'https://koreajoongangdaily.joins.com/news/2025-05-01/business/industry/Korea-designates-Yeosu-as-industrial-crisis-response-area-to-support-petrochemical-firms/2297988', premium: true },
    { id: "prem_12", category: 'Petrochemicals', title: 'PEC Ltd US$165 Million Buyout and Privatization by Liberty Energy Solutions Ltd', date: 'June 19, 2025', source: 'Shawkwei', link: 'https://www.shawkwei.com/pec-ltd-us165-million-buyout-and-privatization-by-liberty-energy-solutions-ltd/?utm_source=chatgpt.com', premium: true },
    { id: "prem_13", category: 'Petrochemicals', title: 'Petrochemical Makers Fret Over Future', date: 'June 19, 2025', source: 'C&EN', link: 'https://cen.acs.org/business/petrochemicals/Petrochemical-makers-fret-over-future/103/web/2025/04', premium: true },
    // Power
    { id: "prem_14", category: 'Power', title: "Realizing Indonesia's Ambitious Renewable Energy Goals Calls New Approach", date: 'June 19, 2025', source: 'IEEFA', link: 'https://ieefa.org/resources/realizing-indonesias-ambitious-renewable-energy-goals-calls-new-approach', premium: true },
    { id: "prem_15", category: 'Power', title: 'Deecell Power Systems Enters Clean Energy Market with Launch of Revolutionary Solar Solutions', date: 'June 19, 2025', source: 'SolarQuarter', link: 'https://solarquarter.com/2025/06/19/deecell-power-systems-enters-clean-energy-market-with-launch-of-revolutionary-solar-solutions/', premium: true },
    { id: "prem_16", category: 'Power', title: 'European Energy Secures AU$130 Million for 137MW Solar PV Portfolio in Australia', date: 'June 19, 2025', source: 'PV Tech', link: 'https://www.pv-tech.org/european-energy-secures-au130-million-for-137mw-solar-pv-portfolio-in-australia/', premium: true },
    { id: "prem_17", category: 'Power', title: 'RERC Approves Tariff for 1000 MWh Battery Storage Project', date: 'June 19, 2025', source: 'Energetica India', link: 'https://www.energetica-india.net/news/rerc-approves-tariff-for-1000-mwh-battery-storage-project', premium: true },
    { id: "prem_18", category: 'Power', title: 'Lazard Says US Energy Storage Cost Reduction in 2025 Offsets Prior Pandemic-Driven Increases', date: 'June 19, 2025', source: 'Energy Storage News', link: 'https://www.energy-storage.news/lazard-says-us-energy-storage-cost-reduction-in-2025-offsets-prior-pandemic-driven-increases/', premium: true },
    // Company News
    { id: "prem_19", category: 'Company News', title: 'Redwire Successfully Completes Integration of Hammerhead Spacecraft for Upcoming European Mission', date: 'June 19, 2025', source: 'Redwire', link: 'https://redwirespace.com/newsroom/redwire-successfully-completes-integration-of-hammerhead-spacecraft-for-upcoming-european-mission/', premium: true },
    { id: "prem_20", category: 'Company News', title: 'Volt Lithium Announces Shareholder Approval of Name Change and Results of Its 2025 Annual and Special Meeting', date: 'June 19, 2025', source: 'BusinessWire', link: 'https://www.businesswire.com/news/home/20250618184801/en/Volt-Lithium-Announces-Shareholder-Approval-of-Name-Change-and-Results-of-Its-2025-Annual-and-Special-Meeting', premium: true },
    { id: "prem_21", category: 'Company News', title: 'Japan Returns to Long-Term LNG Deals as AI Boom Shapes National Energy Plan', date: 'June 19, 2025', source: 'Reuters', link: 'https://www.reuters.com/sustainability/boards-policy-regulation/japan-returns-long-term-lng-deals-ai-boom-national-energy-plan-2025-06-19/', premium: true },
    { id: "prem_22", category: 'Company News', title: 'Poor Grid Planning Could Shift Europe\'s Data Centre Geography, Report Says', date: 'June 19, 2025', source: 'Reuters', link: 'https://www.reuters.com/technology/poor-grid-planning-could-shift-europes-data-centre-geography-report-says-2025-06-18/', premium: true },
    // Renewables
    { id: "prem_23", category: 'Renewables', title: 'Developers Seek Green Light for $15bn Chile Renewables Projects', date: 'June 19, 2025', source: 'BNamericas', link: 'https://www.bnamericas.com/en/news/developers-seek-green-light-for-us15bn-chile-renewables-projects', premium: true },
    { id: "prem_24", category: 'Renewables', title: 'New Marine Energy Taskforce Sets Sights on £50bn Tidal Power Potential', date: 'June 19, 2025', source: 'Energy Live News', link: 'https://www.energylivenews.com/2025/06/19/new-marine-energy-taskforce-sets-sights-on-50bn-tidal-power-potential/', premium: true },
    { id: "prem_25", category: 'Renewables', title: 'Clean Energy China Emissions Peak', date: 'June 19, 2025', source: 'World Economic Forum', link: 'https://www.weforum.org/stories/2025/06/clean-energy-china-emissions-peak/', premium: true },
    { id: "prem_26", category: 'Renewables', title: 'Global Clean Energy Investment Report: China No. 1, America 2, and Emerging Nations Closing Fast', date: 'June 19, 2025', source: 'EnergyTech', link: 'https://www.energytech.com/infrastructure/article/55298215/global-clean-energy-investment-report-china-no-1-america-2-and-emerging-nations-closing-fast', premium: true },
    { id: "prem_27", category: 'Renewables', title: 'Geothermal Energy: Strong Signal from Government', date: 'June 19, 2025', source: 'Yahoo Finance', link: 'https://uk.finance.yahoo.com/news/geothermal-energy-strong-signal-government-110600144.html?guccounter=1&guce_referrer=aHR0cHM6Ly9jaGF0Z3B0LmNvbS8&guce_referrer_sig=AQAAAAh26UaiWtnbeCdFqxeCRB_561qDa5bLVEKVfxzSveIVi6I5sUe3-eflPdAE0czyHdEhfiBe7lrnz-gReJ-du17iVum4D3ZSxRvMDhTP-I1q1zTlCYVAY3Hui6LOd6AnPMVSmnR3nTGN9svi0lHscHP_rk86IBP3FEYudm-imoAo', premium: true },
    { id: "prem_28", category: 'Renewables', title: 'La Caisse Announces Its 2025-2030 Climate Strategy', date: 'June 19, 2025', source: 'Newswire', link: 'https://www.newswire.ca/news-releases/la-caisse-announces-its-2025-2030-climate-strategy-880788092.html', premium: true },
    { id: "prem_29", category: 'Renewables', title: 'Lobbying Intense on Climate Law Credits', date: 'June 19, 2025', source: 'Politico', link: 'http://politico.com/news/2025/06/18/lobbying-intense-on-climate-law-credits-00410668', premium: true }
];
