// /js/articles_past.js
// Data is assigned to the global 'window' object to be accessible by other scripts.
window.pastArticles = [
    // Day 2 (Yesterday)
    [
        { id: "past_d2_1", category: 'Renewables', title: "Renewable Energy Stocks to Add to Your Watchlist", date: 'June 16, 2025', source: 'MarketBeat', link: 'https://www.marketbeat.com/instant-alerts/renewable-energy-stocks-to-add-to-your-watchlist-june-16th-2025-06-16/', premium: true },
        { id: "past_d2_2", category: 'Policy & Markets', title: "Public Money, Green Loans, and Climate Finance", date: 'June 16, 2025', source: 'The Guardian', link: 'https://www.theguardian.com/global-development/2025/jun/16/public-money-green-loans-climate-finance', premium: true },
        { id: "past_d2_3", category: 'Crude Oil', title: "Dow Surges 400 Points, Oil Falls as Iran Reportedly Seeks Israel Truce", date: 'June 16, 2025', source: 'NY Post', link: 'https://nypost.com/2025/06/16/business/dow-surges-400-points-oil-falls-as-iran-reportedly-seeks-israel-truce/', premium: true },
        { id: "past_d2_4", category: 'Crude Oil', title: "Oil Futures, S&P500, Nasdaq: Israel-Iran Trump Tehran Evacuation Warning", date: 'June 16, 2025', source: 'Business Insider', link: 'https://markets.businessinsider.com/news/commodities/oil-futures-sp500-nasdaq-israel-iran-trump-tehran-evacuation-warning-2025-6', premium: true },
        { id: "past_d2_5", category: 'Crude Oil', title: "UK Petrol Prices: Israel-Iran Oil Price Impact", date: 'June 16, 2025', source: 'The Guardian', link: 'http://theguardian.com/business/2025/jun/16/uk-petrol-prices-israel-iran-oil-price', premium: true },
        { id: "past_d2_6", category: 'Power', title: "Today in Energy: US Power Grid Updates", date: 'June 16, 2025', source: 'EIA', link: 'https://www.eia.gov/todayinenergy/detail.php?id=65504', premium: true },
        { id: "past_d2_7", category: 'Natural Gas', title: "EU Gas Demand Set to Fall by 7% by 2030, Ember Report Says", date: 'June 16, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/eu-gas-demand-set-fall-by-7-by-2030-ember-report-says-2025-06-16/', premium: true },
        { id: "past_d2_8", category: 'Power', title: "Gas to Power Journal Updates", date: 'June 16, 2025', source: 'Gas to Power Journal', link: 'https://gastopowerjournal.com/2025/06/16/', premium: true },
        { id: "past_d2_9", category: 'Renewables', title: "EPA's Proposed New Renewable Fuel Standards", date: 'June 16, 2025', source: 'EPA', link: 'https://www.epa.gov/newsreleases/what-they-are-saying-leaders-praise-epas-proposed-new-renewable-fuel-standards', premium: true },
        { id: "past_d2_10", category: 'Crude Oil', title: "Oil Price Rise: Adverse Shock to Global Economy", date: 'June 16, 2025', source: 'The Guardian', link: 'https://www.theguardian.com/business/live/2025/jun/16/oil-price-rise-adverse-shock-global-economy-israel-iran-inflation-petrol-business-live-news-updates', premium: true },
        { id: "past_d2_11", category: 'Crude Oil', title: "What's Not Happening in Middle East Crude Supply Matters More", date: 'June 16, 2025', source: 'Reuters', link: 'https://www.reuters.com/markets/commodities/whats-not-happening-middle-east-crude-supply-matters-more-2025-06-16/', premium: true },
        { id: "past_d2_12", category: 'Policy & Markets', title: "America's Markets Calm as Israel-Iran War Rages", date: 'June 16, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/finance/americas-markets-calm-israel-iran-war-rages-2025-06-16/', premium: true },
        { id: "past_d2_13", category: 'Crude Oil', title: "Oil Prices: Crude Futures WTI, Brent, Israel-Iran", date: 'June 16, 2025', source: 'Barron\'s', link: 'https://www.barrons.com/articles/oil-prices-crude-futures-wti-brent-israel-iran-44d9e2d4', premium: true },
        { id: "past_d2_14", category: 'Policy & Markets', title: "EIA Short-Term Energy Outlook", date: 'June 16, 2025', source: 'EIA', link: 'https://www.eia.gov/outlooks/steo/', premium: true },
        { id: "past_d2_15", category: 'Natural Gas', title: "US EIA's Short-Term Outlook: Natural Gas Demand Outpacing Supply", date: 'June 16, 2025', source: 'S&P Global', link: 'https://www.spglobal.com/commodity-insights/en/news-research/latest-news/natural-gas/061025-us-eias-short-term-outlook-finds-that-natural-gas-demand-is-outpacing-supply', premium: true },
        { id: "past_d2_16", category: 'Crude Oil', title: "China's May Refinery Throughput at 9-Month Low on Plant Overhauls", date: 'June 16, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/chinas-may-refinery-throughput-9-month-low-plant-overhauls-2025-06-16/', premium: true },
        { id: "past_d2_17", category: 'Policy & Markets', title: "Bulls and Bears Energy Market Analysis", date: 'June 16, 2025', source: 'NewCoop', link: 'https://www.newcoop.com/wp-content/uploads/2025/06/Bulls-and-Bears-06162025.pdf', premium: true },
        { id: "past_d2_18", category: 'Policy & Markets', title: "Daily Energy Report", date: 'June 16, 2025', source: 'AF Alhajji', link: 'https://afalhajji.substack.com/p/daily-energy-report-21b', premium: true },
        { id: "past_d2_19", category: 'Company News', title: "Saudi Aramco CEO: Oil and Gas Important in Times of Conflict", date: 'June 16, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/oil-gas-important-times-conflict-saudi-aramco-ceo-says-2025-06-16/', premium: true },
        { id: "past_d2_20", category: 'Renewables', title: "Renewable Energy Remains Cheapest Power Source", date: 'June 16, 2025', source: 'Reuters', link: 'https://www.reuters.com/sustainability/climate-energy/renewable-energy-remains-cheapest-power-builds-new-gas-plants-get-pricier-2025-06-16/', premium: true },
        { id: "past_d2_21", category: 'Power', title: "Guatemala Seeks 700 Megawatts Gas Power Tender", date: 'June 16, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/guatemala-seeks-700-megawatts-gas-power-tender-2025-06-16/', premium: true },
        { id: "past_d2_22", category: 'Policy & Markets', title: "Best in Energy: Market Analysis", date: 'June 16, 2025', source: 'JKemp Energy', link: 'https://jkempenergy.com/2025/06/16/best-in-energy-16-june-2025/', premium: true },
        { id: "past_d2_23", category: 'Petrochemicals', title: "ICIS Energy Commodities Update", date: 'June 16, 2025', source: 'ICIS', link: 'https://www.icis.com/explore/commodities/energy/', premium: true },
        { id: "past_d2_24", category: 'Company News', title: "TotalEnergies Enters 40 Chevron-Operated US Offshore Blocks", date: 'June 16, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/totalenergies-enters-40-chevron-operated-us-offshore-blocks-2025-06-16/', premium: true },
        { id: "past_d2_25", category: 'Earnings', title: "Alvopetro Announces Q2 2025 Dividend", date: 'June 16, 2025', source: 'Newswire', link: 'https://www.newswire.ca/news-releases/alvopetro-announces-q2-2025-dividend-of-us-0-10-per-share-and-reminder-of-upcoming-agm-814482338.html', premium: true },
        { id: "past_d2_26", category: 'Policy & Markets', title: "API Statement on Senate Finance Committee Reconciliation Proposal", date: 'June 16, 2025', source: 'API', link: 'https://www.api.org/news-policy-and-issues/news/2025/06/16/api-statement-on-senate-finance-committee-reconciliation-proposal-final', premium: true },
        { id: "past_d2_27", category: 'Policy & Markets', title: "US Senate Bill Would Shrink Tax Credit for Biofuels Made from Foreign Feedstocks", date: 'June 16, 2025', source: 'Reuters', link: 'https://www.reuters.com/sustainability/climate-energy/us-senate-bill-would-shrink-tax-credit-biofuels-made-foreign-feedstocks-2025-06-16/', premium: true },
        { id: "past_d2_28", category: 'Policy & Markets', title: "US Stock Futures Steady with Focus on Mideast Tensions", date: 'June 16, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/us-stock-futures-steady-with-focus-mideast-tensions-fed-meeting-2025-06-16/', premium: true },
        { id: "past_d2_29", category: 'Crude Oil', title: "Maximum Economic Pain: Oil Prices Could Skyrocket if Iran-Israel Attacks Escalate", date: 'June 16, 2025', source: 'BNN Bloomberg', link: 'https://www.bnnbloomberg.ca/business/2025/06/16/maximum-economic-pain-oil-prices-could-skyrocket-if-iran-israel-attacks-escalates-expert-says/', premium: true },
        { id: "past_d2_30", category: 'Earnings', title: "Enbridge Could Be a No-Brainer Buy in June", date: 'June 16, 2025', source: 'The Motley Fool', link: 'https://www.fool.ca/2025/06/16/enbridge-could-be-a-no-brainer-buy-in-june/', premium: true },
        { id: "past_d2_31", category: 'Policy & Markets', title: "World Bank Ends Ban on Nuclear Energy Projects", date: 'June 16, 2025', source: 'Reuters', link: 'https://www.reuters.com/sustainability/climate-energy/world-bank-end-ban-nuclear-energy-projects-still-debating-upstream-gas-2025-06-11/', premium: true }
    ],
    // Day 3
    [
        { id: "past_d3_1", category: 'Crude Oil', title: "Oil Prices Could Top $90 as Israel-Iran Conflict Escalates", date: 'June 15, 2025', source: 'Yahoo Finance', link: 'https://finance.yahoo.com/news/oil-prices-could-top-90-as-israel-iran-conflict-escalates-tensions-in-middle-east-152247868.html', premium: true },
        { id: "past_d3_2", category: 'Crude Oil', title: "Israel's Airstrikes on Iran Trigger Oil Market Surge", date: 'June 15, 2025', source: 'NewsX', link: 'https://www.newsx.com/business/israels-airstrikes-on-iran-trigger-oil-market-surge-4070/', premium: true },
        { id: "past_d3_3", category: 'Crude Oil', title: "Crude Prices Rise as Exxon, Israel-Iran Strikes", date: 'June 15, 2025', source: 'Houston Chronicle', link: 'https://www.houstonchronicle.com/business/energy/article/crude-prices-rise-exxon-israel-iran-strikes-20372692.php', premium: true },
        { id: "past_d3_4", category: 'Policy & Markets', title: "Israel-Iran Attack Impact on Oil and Stock Market", date: 'June 15, 2025', source: 'AP News', link: 'https://apnews.com/article/israel-iran-attack-oil-stock-market-fe6d0aed826aec5f041ed492f19ea12d', premium: true },
        { id: "past_d3_5", category: 'Policy & Markets', title: "Energy Stocks Climb with Rising Oil and Gas Prices", date: 'June 15, 2025', source: 'Finimize', link: 'https://finimize.com/content/energy-stocks-climb-with-rising-oil-and-gas-prices', premium: true },
        { id: "past_d3_6", category: 'Policy & Markets', title: "Axios Generate Newsletter", date: 'June 15, 2025', source: 'Axios', link: 'https://www.axios.com/newsletters/axios-generate-de02fa20-479d-11f0-b5d5-fd08b1169e59', premium: true },
        { id: "past_d3_7", category: 'Earnings', title: "Further Upside for Journey Energy Inc. Shares", date: 'June 15, 2025', source: 'Simply Wall St', link: 'https://simplywall.st/stocks/ca/energy/tsx-joy/journey-energy-shares/news/further-upside-for-journey-energy-inc-tsejoy-shares-could-in', premium: true },
        { id: "past_d3_8", category: 'Renewables', title: "Adani Green Energy Tops ESG Rankings in Power Sector", date: 'June 15, 2025', source: 'Urban Acres', link: 'https://urbanacres.in/adani-green-energy-tops-esg-rankings-in-power-sector/', premium: true },
        { id: "past_d3_9", category: 'Crude Oil', title: "As the Middle East Erupts, Investors Choose Oil and Safe Havens Over Stocks", date: 'June 15, 2025', source: 'Energy News', link: 'https://energynews.oedigital.com/crude-oil/2025/06/13/as-the-middle-east-erupts-investors-choose-oil-and-safe-havens-over-stocks', premium: true },
        { id: "past_d3_10", category: 'Policy & Markets', title: "Canada Alberta Secession Referendum: Mark Carney", date: 'June 15, 2025', source: 'Wall Street Journal', link: 'https://www.wsj.com/world/americas/canada-alberta-secession-referendum-mark-carney-4b1f45ec', premium: true },
        { id: "past_d3_11", category: 'Power', title: "Russia's Rosatom to Lead Consortium Building First Nuclear Power Plant in Kazakhstan", date: 'June 15, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/russias-rosatom-lead-consortium-build-first-nuclear-power-plant-kazakhstan-2025-06-14/', premium: true }
    ],
    // Day 4
    [
        { id: "past_d4_1", category: 'Policy & Markets', title: "Pro-Business Policy, Energy Tax Cuts Support America", date: 'June 14, 2025', source: 'Deseret News', link: 'https://www.deseret.com/opinion/2025/06/14/pro-business-policy-energy-tax-cuts-support-america/', premium: true },
        { id: "past_d4_2", category: 'Policy & Markets', title: "Global Markets: Investors React to Middle East Tensions", date: 'June 14, 2025', source: 'Reuters', link: 'https://www.reuters.com/world/middle-east/global-markets-investors-pix-2025-06-14/', premium: true },
        { id: "past_d4_3", category: 'Crude Oil', title: "Oil Surges, Stock Markets, Dollar, Airlines: Israel Attack on Iran", date: 'June 14, 2025', source: 'The Guardian', link: 'https://www.theguardian.com/business/live/2025/jun/13/oil-surges-stock-markets-dollar-airlines-israel-attack-iran-business-live', premium: true },
        { id: "past_d4_4", category: 'Crude Oil', title: "US Drillers Cut Oil/Gas Rigs for 7th Week, Lowest Since 2021", date: 'June 14, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/us-drillers-cut-oilgas-rigs-7th-week-lowest-since-2021-baker-hughes-says-2025-06-13/', premium: true },
        { id: "past_d4_5", category: 'Policy & Markets', title: "US Energy Chief Monitoring Global Energy Supply Impacts", date: 'June 14, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/us-energy-chief-monitoring-any-impacts-global-energy-supply-2025-06-13/', premium: true },
        { id: "past_d4_6", category: 'Natural Gas', title: "US NatGas Prices Climb 2% on Soaring Oil Futures After Israel Strikes Iran", date: 'June 14, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/us-natgas-prices-climb-2-soaring-oil-futures-after-israel-strikes-iran-2025-06-13/', premium: true },
        { id: "past_d4_7", category: 'Crude Oil', title: "Israel-Iran War: Strait of Hormuz Closure Could Send Oil Prices Soaring", date: 'June 14, 2025', source: 'Fortune', link: 'https://fortune.com/2025/06/14/israel-iran-war-strait-of-hormuz-closure-oil-prices-energy-infrastructure-pars-field-natural-gas/', premium: true },
        { id: "past_d4_8", category: 'Policy & Markets', title: "Geopolitical Volatility in Middle East: Navigating Energy Markets", date: 'June 14, 2025', source: 'AInvest', link: 'https://www.ainvest.com/news/geopolitical-volatility-middle-east-navigating-energy-markets-defense-opportunities-2506/', premium: true },
        { id: "past_d4_9", category: 'Renewables', title: "Green Energy News", date: 'June 14, 2025', source: 'Green Energy Times', link: 'https://www.greenenergytimes.org/2025/06/june-14-green-energy-news-12/', premium: true }
    ],
    // Day 5
    [
        { id: "past_d5_1", category: 'Crude Oil', title: "Israel Strike Puts All Eyes on Hormuz, $100 Oil", date: 'June 13, 2025', source: 'Reuters', link: 'https://www.reuters.com/markets/commodities/israel-strike-puts-all-eyes-hormuz-100-oil-bousso-2025-06-13/', premium: true },
        { id: "past_d5_2", category: 'Crude Oil', title: "Oil Prices Jump More Than 4% After Israel Strikes Iran", date: 'June 13, 2025', source: 'Reuters', link: 'https://www.reuters.com/world/china/oil-prices-jump-more-than-4-after-israel-strikes-iran-2025-06-13/', premium: true },
        { id: "past_d5_3", category: 'Crude Oil', title: "Traders Pile into $80 US Oil Bets as Tensions Rise in Middle East", date: 'June 13, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/traders-pile-into-80-us-oil-bets-tensions-rise-middle-east-2025-06-13/', premium: true },
        { id: "past_d5_4", category: 'Power', title: "Batteries, Grid State of Reliability: NERC", date: 'June 13, 2025', source: 'Utility Dive', link: 'https://www.utilitydive.com/news/batteries-grid-state-of-reliability-nerc/750649/', premium: true },
        { id: "past_d5_5", category: 'Power', title: "Levelized Cost of Electricity: Limitations Analysis", date: 'June 13, 2025', source: 'Utility Dive', link: 'https://www.utilitydive.com/news/levelized-cost-electricity-lcoe-limitations-analysis-catf-report/750657/', premium: true },
        { id: "past_d5_6", category: 'Power', title: "SPP Fast Track Interconnection: ERAS FERC", date: 'June 13, 2025', source: 'Utility Dive', link: 'https://www.utilitydive.com/news/spp-fast-track-interconnection-eras-ferc/750669/', premium: true },
        { id: "past_d5_7", category: 'Power', title: "Electric Power Sector Issues to Watch", date: 'June 13, 2025', source: 'Utility Dive', link: 'https://www.utilitydive.com/news/electric-power-sector-issues-to-watch-prices-demand-reliability-renewables-nuclear-vpp-transmission/736492/', premium: true },
        { id: "past_d5_8", category: 'Renewables', title: "Canada's Largest Off-Grid Solar Project Breaks Ground", date: 'June 13, 2025', source: 'PV Magazine', link: 'https://www.pv-magazine.com/2025/06/13/canadas-largest-off-grid-solar-project-breaks-ground/', premium: true },
        { id: "past_d5_9", category: 'Renewables', title: "TNO, Solarge Unveil Lightweight Perovskite Solar Module Prototype", date: 'June 13, 2025', source: 'PV Magazine', link: 'https://www.pv-magazine.com/2025/06/13/tno-solarge-unveil-lightweight-perovskite-solar-module-prototype/', premium: true }
    ],
    // Day 6
    [
        { id: "past_d6_1", category: 'Crude Oil', title: "Projected Crude Oil Dip", date: 'June 11, 2025', source: 'Axios', link: 'https://www.axios.com/2025/06/11/projected-crude-oil-dip/', premium: true },
        { id: "past_d6_2", category: 'Power', title: "Texas Gas Power Plants and AI", date: 'June 11, 2025', source: 'Texas Tribune', link: 'https://www.texastribune.org/2025/06/11/texas-gas-power-plants-ai/', premium: true },
        { id: "past_d6_3", category: 'Natural Gas', title: "Secretaries Burgum, Wright Join JERA and US LNG Producers", date: 'June 11, 2025', source: 'DOI', link: 'https://www.doi.gov/pressreleases/secretaries-burgum-wright-join-jera-and-us-lng-producers', premium: true },
        { id: "past_d6_4", category: 'Crude Oil', title: "US Oil Output Decline, Demand OPEC", date: 'June 11, 2025', source: 'MRT', link: 'https://www.mrt.com/business/oil/article/us-oil-output-decline-demand-opec-20323766.php', premium: true },
        { id: "past_d6_5", category: 'Petrochemicals', title: "Indian Refineries Plan Green Hydrogen Projects Worth Rs2 Trillion", date: 'June 11, 2025', source: 'ICIS', link: 'https://www.icis.com/explore/resources/news/2025/06/11/11109495/indian-refineries-plan-green-hydrogen-projects-worth-rs2-trillion/', premium: true }
    ],
    // Day 7
    [
        { id: "past_d7_1", category: 'Power', title: "Nokia Expands IP Routing Portfolio to Utilities with New Platforms", date: 'June 12, 2025', source: 'Seeking Alpha', link: 'https://seekingalpha.com/pr/20135065-nokia-expands-ip-routing-portfolio-to-utilities-with-new-platforms-to-boost-smart-grid', premium: true },
        { id: "past_d7_2", category: 'Earnings', title: "Energy Transfer Has A Strong Yield And Growth Potential", date: 'June 12, 2025', source: 'Seeking Alpha', link: 'https://seekingalpha.com/article/4791526-energy-transfer-has-a-strong-yield-and-growth-potential', premium: true },
        { id: "past_d7_3", category: 'Earnings', title: "Energy Transfer Is My Largest Holding For Good Reason", date: 'June 12, 2025', source: 'Seeking Alpha', link: 'https://seekingalpha.com/article/4794381-energy-transfer-is-my-largest-holding-for-good-reason', premium: true },
        { id: "past_d7_4", category: 'Earnings', title: "Devon Energy: Creating Value With Low Oil Prices", date: 'June 12, 2025', source: 'Seeking Alpha', link: 'https://seekingalpha.com/article/4794278-devon-energy-creating-value-with-low-oil-prices', premium: true },
        { id: "past_d7_5", category: 'Earnings', title: "Duke Energy Keeps Sparking", date: 'June 12, 2025', source: 'Seeking Alpha', link: 'https://seekingalpha.com/article/4794276-duke-energy-keeps-sparking', premium: true },
        { id: "past_d7_6", category: 'Company News', title: "Capital Clean Energy Carriers: A New Name, A New Growth Engine", date: 'June 12, 2025', source: 'Seeking Alpha', link: 'https://seekingalpha.com/article/4794442-capital-clean-energy-carriers-a-new-name-a-new-growth-engine-a-compelling-buy', premium: true },
        { id: "past_d7_7", category: 'Earnings', title: "Clearway Energy: 6% Yield On Utilities, Undervalued, 20 Straight Hikes", date: 'June 12, 2025', source: 'Seeking Alpha', link: 'https://seekingalpha.com/article/4793020-clearway-energy-6-percent-yield-on-utilities-undervalued-20-straight-hikes', premium: true },
        { id: "past_d7_8", category: 'Power', title: "EPA Greenhouse Gas, Mercury Power Plant Rules Finalized", date: 'June 12, 2025', source: 'CT Mirror', link: 'https://ctmirror.org/2025/06/12/epa-greenhouse-gas-mercury-power-plant-rules/', premium: true },
        { id: "past_d7_9", category: 'Power', title: "Victorian Grid Under Pressure As Coal And Gas Outages Hit Supply", date: 'June 12, 2025', source: 'The Australian', link: 'https://www.theaustralian.com.au/business/victorian-grid-under-pressure-as-coal-and-gas-outages-hit-supply/news-story/e38ab0d8c0e7f74853e892eb8f23459e', premium: true },
        { id: "past_d7_10", category: 'Power', title: "Trump EPA Pollution Rules Overturned", date: 'June 12, 2025', source: 'The Guardian', link: 'https://www.theguardian.com/us-news/2025/jun/12/trump-epa-pollution-rules', premium: true },
        { id: "past_d7_11", category: 'Crude Oil', title: "JP Morgan Maintains 2025 Forecast for Oil Prices in Low to Mid-$60s", date: 'June 12, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/jp-morgan-maintains-2025-forecast-oil-prices-low-to-mid-60s-2025-06-12/', premium: true },
        { id: "past_d7_12", category: 'Crude Oil', title: "Saudi Arabia Is Grabbing Oil Market Share, But It Can Open The Tap Only So Far", date: 'June 12, 2025', source: 'Wall Street Journal', link: 'https://www.wsj.com/business/energy-oil/saudi-arabia-is-grabbing-oil-market-share-but-it-can-open-the-tap-only-so-far-6f79fe49', premium: true },
        { id: "past_d7_13", category: 'Crude Oil', title: "This Crucial Corner of the Energy Market Is At High Risk from All-Out War", date: 'June 12, 2025', source: 'MarketWatch', link: 'https://www.marketwatch.com/story/this-crucial-corner-of-the-energy-market-is-at-high-risk-from-an-all-out-war-between-israel-and-iran-and-its-not-oil-0d26bfbf', premium: true },
        { id: "past_d7_14", category: 'Company News', title: "NextDecade Signs $9 Billion Contracts With Bechtel for LNG Sites", date: 'June 12, 2025', source: 'Reuters', link: 'https://www.reuters.com/business/energy/nextdecade-signs-9-billion-contracts-with-bechtel-construction-lng-sites-2025-06-12/', premium: true },
        { id: "past_d7_15", category: 'Company News', title: "TotalEnergies to Collaborate With Mistral AI to Increase Efficiency", date: 'June 12, 2025', source: 'Yahoo Finance', link: 'https://finance.yahoo.com/news/totalenergies-collaborate-mistral-ai-increase-061500813.html', premium: true },
        { id: "past_d7_16", category: 'Company News', title: "US Energy Loan Office to Fund More Projects in 2025", date: 'June 12, 2025', source: 'Yahoo Finance', link: 'https://finance.yahoo.com/news/us-energy-loan-office-fund-181503597.html', premium: true },
        { id: "past_d7_17", category: 'Natural Gas', title: "JERA Expects US LNG Share To Reach 30% After Latest Gulf Coast Deals", date: 'June 12, 2025', source: 'S&P Global', link: 'https://www.spglobal.com/commodity-insights/en/news-research/latest-news/lng/061225-jera-expects-us-lng-share-to-reach-30-after-latest-55-mil-mtyear-gulf-coast-deals', premium: true },
        { id: "past_d7_18", category: 'Natural Gas', title: "Oil Futures Crude Down On Renewed Tariff Fears", date: 'June 12, 2025', source: 'S&P Global', link: 'https://www.spglobal.com/commodity-insights/en/news-research/latest-news/crude-oil/061225-oil-futures-crude-down-on-renewed-tariff-fears', premium: true },
        { id: "past_d7_19", category: 'Policy & Markets', title: "Trump's Energy Dominance Agenda Could Be Ravaged By Section 899", date: 'June 12, 2025', source: 'Reuters', link: 'https://www.reuters.com/markets/commodities/trumps-energy-dominance-agenda-could-be-ravaged-by-section-899-2025-06-12/', premium: true },
        { id: "past_d7_20", category: 'Company News', title: "Trump to Attend AI + Energy Summit in Pittsburgh", date: 'June 12, 2025', source: 'Reuters', link: 'https://www.reuters.com/world/us/trump-attend-ai-energy-summit-pittsburgh-2025-06-12/', premium: true }
    ]
];
